// <auto-generated />
using System;
using ICS_Project.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ICS_Project.DAL.Migrations
{
    [DbContext(typeof(MediaPlayerDbContext))]
    partial class MediaPlayerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("ICS_Project.DAL.Entities.MultimediaFileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FileType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MultimediaFiles");
                });

            modelBuilder.Entity("ICS_Project.DAL.Entities.PlaylistEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FileCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalDuration")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("ICS_Project.DAL.Entities.TimeAddedEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MultimediaFileId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MultimediaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MultimediaFileId");

                    b.HasIndex("PlaylistId");

                    b.ToTable("TimesAdded");
                });

            modelBuilder.Entity("ICS_Project.DAL.Entities.TimeAddedEntity", b =>
                {
                    b.HasOne("ICS_Project.DAL.Entities.MultimediaFileEntity", "MultimediaFileEntity")
                        .WithMany()
                        .HasForeignKey("MultimediaFileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ICS_Project.DAL.Entities.PlaylistEntity", "PlaylistEntity")
                        .WithMany("MultimediaFiles")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MultimediaFileEntity");

                    b.Navigation("PlaylistEntity");
                });

            modelBuilder.Entity("ICS_Project.DAL.Entities.PlaylistEntity", b =>
                {
                    b.Navigation("MultimediaFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
