/**
* @file precedence_table.c
 * @brief Implementation of precedence table used in expression parsing.
 *
 *
 * Authors:
 * - Juraj Mesík (xmesikj00), 2025
 */

#include "precedence_table.h"

#define ROW(...) { __VA_ARGS__ }

// rows are items on top of the stack
// columns are input tokens
const prec_table_op table[TABLE_SIZE][TABLE_SIZE] = {
    // T_PLUS
    ROW(REDUCTION, REDUCTION, SHIFT,     SHIFT,     SHIFT,
        REDUCTION, REDUCTION, REDUCTION, REDUCTION, REDUCTION,
        REDUCTION, REDUCTION, REDUCTION, SHIFT, SHIFT, SHIFT, SHIFT, REDUCTION, SHIFT),

    // T_MINUS
    ROW(REDUCTION, REDUCTION, SHIFT,     SHIFT,     SHIFT,
        REDUCTION, REDUCTION, REDUCTION, REDUCTION, REDUCTION,
        REDUCTION, REDUCTION, REDUCTION, SHIFT, ERROR, SHIFT, SHIFT, REDUCTION, SHIFT),

    // T_MULTIPLY
    ROW(REDUCTION, REDUCTION, REDUCTION, REDUCTION, SHIFT,
        REDUCTION, REDUCTION, REDUCTION, REDUCTION, REDUCTION,
        REDUCTION, REDUCTION, REDUCTION, SHIFT, SHIFT, SHIFT, SHIFT, REDUCTION, SHIFT),

    // T_DIVIDE
    ROW(REDUCTION, REDUCTION, REDUCTION, REDUCTION, SHIFT,
        REDUCTION, REDUCTION, REDUCTION, REDUCTION, REDUCTION,
        REDUCTION, REDUCTION, REDUCTION, SHIFT, ERROR, SHIFT, SHIFT, REDUCTION, SHIFT),

    // T_BRACKET_OPEN
    ROW(SHIFT,     SHIFT,     SHIFT,     SHIFT,     SHIFT,
        EQUAL,     SHIFT,     SHIFT,     SHIFT,     SHIFT,
        SHIFT,     SHIFT,     ERROR,     SHIFT, SHIFT, SHIFT, SHIFT, SHIFT, SHIFT),

    // T_BRACKET_CLOSE
    ROW(REDUCTION, REDUCTION, REDUCTION, REDUCTION, ERROR,
        REDUCTION, REDUCTION, REDUCTION, REDUCTION, REDUCTION,
        REDUCTION, REDUCTION, REDUCTION, ERROR, ERROR, ERROR, ERROR, REDUCTION, SHIFT),

    // T_LESS
    ROW(SHIFT,     SHIFT,     SHIFT,     SHIFT,     SHIFT,
        REDUCTION, REDUCTION, REDUCTION, REDUCTION, REDUCTION,
        REDUCTION, REDUCTION, REDUCTION, SHIFT, SHIFT, SHIFT, SHIFT, REDUCTION, SHIFT),

    // T_LARGER
    ROW(SHIFT,     SHIFT,     SHIFT,     SHIFT,     SHIFT,
        REDUCTION, REDUCTION, REDUCTION, REDUCTION, REDUCTION,
        REDUCTION, REDUCTION, REDUCTION, SHIFT, SHIFT, SHIFT, SHIFT, REDUCTION, SHIFT),

    // T_LESS_EQUALS
    ROW(SHIFT,     SHIFT,     SHIFT,     SHIFT,     SHIFT,
        REDUCTION, REDUCTION, REDUCTION, REDUCTION, REDUCTION,
        REDUCTION, REDUCTION, REDUCTION, SHIFT, SHIFT, SHIFT, SHIFT, REDUCTION, SHIFT),

    // T_LARGER_EQUALS
    ROW(SHIFT,     SHIFT,     SHIFT,     SHIFT,     SHIFT,
        REDUCTION, REDUCTION, REDUCTION, REDUCTION, REDUCTION,
        REDUCTION, REDUCTION, REDUCTION, SHIFT, SHIFT, SHIFT, SHIFT, REDUCTION, SHIFT),

    // T_EQUAL
    ROW(SHIFT,     SHIFT,     SHIFT,     SHIFT,     SHIFT,
        REDUCTION, REDUCTION, REDUCTION, REDUCTION, REDUCTION,
        REDUCTION, REDUCTION, REDUCTION, SHIFT, SHIFT, SHIFT, SHIFT, SHIFT, SHIFT),

    // T_NOT_EQUAL
    ROW(SHIFT,     SHIFT,     SHIFT,     SHIFT,     SHIFT,
        REDUCTION, REDUCTION, REDUCTION, REDUCTION, REDUCTION,
        REDUCTION, REDUCTION, REDUCTION, SHIFT, SHIFT, SHIFT, SHIFT, SHIFT, SHIFT),

    // T_STACK_BOTTOM
    ROW(SHIFT,     SHIFT,     SHIFT,     SHIFT,     SHIFT,
        EOE,     SHIFT,     SHIFT,     SHIFT,     SHIFT,
        SHIFT,     SHIFT,     ERROR,     SHIFT, SHIFT, SHIFT, SHIFT, SHIFT, SHIFT),

    // T_NUM
    ROW(REDUCTION, REDUCTION, REDUCTION, REDUCTION, ERROR,
        REDUCTION, REDUCTION, REDUCTION, REDUCTION, REDUCTION,
        REDUCTION, REDUCTION, REDUCTION, ERROR, ERROR, ERROR, ERROR, REDUCTION, ERROR),

    // T_STRING
    ROW(REDUCTION, ERROR,     REDUCTION, ERROR,     REDUCTION,
        REDUCTION, REDUCTION, REDUCTION, REDUCTION, REDUCTION,
        REDUCTION, REDUCTION, REDUCTION, ERROR, ERROR, ERROR, ERROR, REDUCTION, ERROR),

    // T_NULL
    ROW(ERROR,     ERROR,     ERROR,     ERROR,     ERROR,
        REDUCTION, REDUCTION, REDUCTION, REDUCTION, REDUCTION,
        REDUCTION, REDUCTION, REDUCTION,     ERROR, ERROR, ERROR, ERROR, REDUCTION, ERROR),

    // T_IDENTIFIER
    ROW(REDUCTION, REDUCTION, REDUCTION,     REDUCTION,     ERROR,
        REDUCTION, REDUCTION, REDUCTION, REDUCTION, REDUCTION,
        REDUCTION, REDUCTION, REDUCTION,     ERROR, ERROR, ERROR, ERROR, REDUCTION, ERROR),

    // T_IS
    ROW(SHIFT, SHIFT, SHIFT, SHIFT, SHIFT,
        REDUCTION, SHIFT, SHIFT, SHIFT, SHIFT,
        REDUCTION, REDUCTION, REDUCTION, SHIFT, SHIFT, SHIFT, SHIFT, ERROR, SHIFT),
    
    // T_TYPE_KEYWORD
    ROW(REDUCTION, REDUCTION, REDUCTION, REDUCTION, REDUCTION,
        REDUCTION, REDUCTION, REDUCTION, REDUCTION, REDUCTION,
        REDUCTION, REDUCTION, REDUCTION, ERROR, ERROR, ERROR, ERROR, REDUCTION, ERROR),
    
};
