CC=gcc
CFLAGS=-Wall -std=c11 -pedantic -lm
FILES=btree.c ../btree.c ../test_util.c ../test.c ../character.c

.PHONY: test clean

test: $(FILES)
	@ rm -rf test
	$(CC) $(CFLAGS) -o $@ $(FILES)
	@ ./test
clean:
	rm -f test
